# Generated using https://godot-build-options-generator.github.io

module_bmp_enabled = "no"
module_bullet_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gdnative_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_noise_enabled = "no"
module_opensimplex_enabled = "no"
module_openxr_enabled = "no"
module_opus_enabled = "no"
module_regex_enabled = "no"
module_tga_enabled = "no"
module_theora_enabled = "no"
module_upnp_enabled = "no"
module_visual_script_enabled = "no"
module_webm_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
