name: itch.io upload

on:
  push:
    paths:
      - "version"
      - ".github/workflows/upload-itchio.yml"

env:
  ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
  WORKING_DIRECTORY: game

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Delete iOS icons
        run: rm -rf $WORKING_DIRECTORY/AppIcons

      - name: Godot HTML5 export
        uses: dulvui/godot-html-export@v0.0.1
        with:
          working-directory: $WORKING_DIRECTORY

      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: $WORKING_DIRECTORY/html5
          api-key: $ITCHIO_API_KEY
          user: simondalvai
          game: ball2box
          channel: "HTML5 / Playable in browser"




